### PR TITLE
Fix: progress text in stepper circle

### PR DESCRIPTION
**Pull request by sally**
This addresses Issue #26 

For more details on how this fix works, visit [PR #124](https://github.com/whynotearth/foodouken.com/pull/124) on Foodouken.

I had to reduce the text-size on the progress text because the text with `text-sm` applied did not fit in one line inside a `w-16 h-16` container.

### CODE REVIEW

**Comment by mort3za** [comment]
I still see the issues on iPhone 8

image

**Comment by mort3za** [comment]
Also, Please change the base branch to staging. I've added the staging branch as our target for PRs.

**Comment by sally** [comment]
@mort3za Changed base branch of PR to `staging` as requested. Also fixed the invisible Progress Text - the problem was that it had a `text-white` utility class on it.. :) Tested on iPhone 8

image

**Comment by mort3za** [comment]
Thank you. the progress circle color has still issue on iPhone 8 Safari @sally 

image

**Pull request merged**
