### PR TITLE
add the props for receive the function for be able the keyup event

### PR DESCRIPTION
**Pull request by IgorVieira**

### CODE REVIEW

**Comment by bamboochow** [comment]
@mort3za can you take a look at this?

**Comment by mort3za** [comment]
This should be done easier in Vue. https://github.com/whynotearth/Volkswagen-email-corporate-communications-CMS/pull/323

**Comment by IgorVieira** [comment]
@mort3za please, wait I solved this issue using javascript because vuejs don't have a good support for keyup events (we have a lot article talking about that problem) but in this case it's javascript, a simple function written in vanilla and works perfectly

**Comment by IgorVieira** [comment]
Also we don't have any attribute for keyup events in buttons it's only for input tags and that's the reason for I have changed the button tag for an input tag

**Pull request closed without merging**
